---
title: "Data Transformation"
author: "Group 17"
date: "11/29/2021"
output: html_document
---

# Data Transformation

```{r}
df = read.csv("Speed Dating Data.csv")
library(tidyverse)
```

```{r}
df = read.csv("Speed Dating Data.csv")

col_common = c("iid", "pid", "gender", "match", "age", "field", "race", "from", "income", "goal", "career", "wave")
df_1 = df[c(col_common, "attr1_1", "sinc1_1", "intel1_1", "fun1_1", "amb1_1")]
df_2 = df[c(col_common, "attr2_1", "sinc2_1", "intel2_1", "fun2_1", "amb2_1")]
df_3 = df[c(col_common, "attr3_1", "sinc3_1", "intel3_1", "fun3_1", "amb3_1")]
df_4 = df[c(col_common, "attr4_1", "sinc4_1", "intel4_1", "fun4_1", "amb4_1")]
df_5 = df[c(col_common, "attr5_1", "sinc5_1", "intel5_1", "fun5_1", "amb5_1")]
colnames(df_1) = c("iid", "pid", "gen", "mch", "age", "fld", "rce", "frm", "inc",
                   "goal", "car", "wve", "at1", "si1", "in1", "fu1", "am1")
colnames(df_2) = c("iid", "pid", "gen", "mch", "age", "fld", "rce", "frm", "inc",
                   "goal", "car", "wve", "at1", "si1", "in1", "fu1", "am1")
colnames(df_3) = c("iid", "pid", "gen", "mch", "age", "fld", "rce", "frm", "inc",
                   "goal", "car", "wve", "at1", "si1", "in1", "fu1", "am1")
colnames(df_4) = c("iid", "pid", "gen", "mch", "age", "fld", "rce", "frm", "inc",
                   "goal", "car", "wve", "at1", "si1", "in1", "fu1", "am1")
colnames(df_5) = c("iid", "pid", "gen", "mch", "age", "fld", "rce", "frm", "inc",
                   "goal", "car", "wve", "at1", "si1", "in1", "fu1", "am1")


df_transformed = df %>% 
  select("iid", "pid", "gender", "match", "age", "field", "race", "from", "income", "goal", "career", "wave",
         "attr1_1", "sinc1_1", "intel1_1", "fun1_1", "amb1_1",
         "attr2_1", "sinc2_1", "intel2_1", "fun2_1", "amb2_1",
         "attr3_1", "sinc3_1", "intel3_1", "fun3_1", "amb3_1",
         "attr4_1", "sinc4_1", "intel4_1", "fun4_1", "amb4_1",
         "attr5_1", "sinc5_1", "intel5_1", "fun5_1", "amb5_1")



#write.csv(df_transformed,"Transformed Data.csv", row.names = FALSE)
```


